#!/usr/bin/env bash

#build command
cabal new-build --upgrade-dependencies --force-reinstalls
cabal install \
  --install-method=copy --overwrite-policy=always \
  --installdir=$XDG_CONFIG_HOME/xmonad
echo Copying $XDG_CONFIG_HOME/xmonad/my-xmonad to "$1"
rsync $XDG_CONFIG_HOME/xmonad/my-xmonad "$1"
